// Mocks generated by Mockito 5.4.6 from annotations
// in burncare_front/test/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:burncare_front/models/auth_response.dart' as _i3;
import 'package:burncare_front/services/api_client.dart' as _i2;
import 'package:burncare_front/services/auth_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_1 extends _i1.SmartFake implements _i3.AuthResponse {
  _FakeAuthResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i5.Future<_i3.AuthResponse> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i5.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i5.Future<_i3.AuthResponse>);

  @override
  _i5.Future<_i3.AuthResponse> register({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? password,
    required String? profession,
    String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #password: password,
              #profession: profession,
              #role: role,
            }),
            returnValue: _i5.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(
                this,
                Invocation.method(#register, [], {
                  #firstName: firstName,
                  #lastName: lastName,
                  #email: email,
                  #password: password,
                  #profession: profession,
                  #role: role,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AuthResponse>);

  @override
  _i5.Future<_i3.AuthResponse> updateProfile(
    String? email,
    String? firstName,
    String? lastName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [email, firstName, lastName]),
            returnValue: _i5.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(
                this,
                Invocation.method(#updateProfile, [email, firstName, lastName]),
              ),
            ),
          )
          as _i5.Future<_i3.AuthResponse>);

  @override
  _i5.Future<void> changePassword(String? email, String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [email, newPassword]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
